# Generated by Django 4.1.1 on 2022-10-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ptype", models.CharField(max_length=25, unique=True)),
                ("no_effect", models.CharField(blank=True, max_length=75)),
                ("super_effective_attack", models.CharField(blank=True, max_length=75)),
                ("ineffective_attack", models.CharField(blank=True, max_length=75)),
                ("weak_against", models.CharField(blank=True, max_length=75)),
                ("strong_against", models.CharField(blank=True, max_length=75)),
                ("no_damage", models.CharField(blank=True, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=500)),
                ("image_url", models.CharField(max_length=250)),
                (
                    "poke_location",
                    models.ManyToManyField(
                        related_name="locations", to="pokemon.location"
                    ),
                ),
                (
                    "poke_type",
                    models.ManyToManyField(related_name="types", to="pokemon.type"),
                ),
            ],
        ),
    ]
